version: '3'

volumes:
  static:
  database:
  esdata:
  redis_data:

services:
  hellodjango.rest.framework.tutorial:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: hellodjango_rest_framework_tutorial
    container_name: hellodjango_rest_framework_tutorial
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    expose:
      - "8000"
    command: /start.sh
    depends_on:
      - elasticsearch
      - redis

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: hellodjango_rest_framework_tutorial_nginx
    container_name: hellodjango_rest_framework_tutorial_nginx
    volumes:
      - static:/apps/hellodjango_rest_framework_tutorial/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - hellodjango.rest.framework.tutorial

  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: hellodjango_rest_framework_tutorial_elasticsearch
    container_name: hellodjango_rest_framework_tutorial_elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536

  redis:
    image: 'bitnami/redis:5.0'
    container_name: hellodjango_rest_framework_tutorial_redis
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    env_file:
      - .envs/.production
