# Generated by Django 2.2.23 on 2021-06-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pid',
            new_name='parent',
        ),
    ]
