# Generated by Django 2.2.23 on 2021-06-21 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210607_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeHole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.TreeHole')),
            ],
            options={
                'verbose_name': '树洞',
                'verbose_name_plural': '树洞',
                'ordering': ['-created_time'],
            },
        ),
    ]
